
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: i15-1_notebook_test
spec:
  entrypoint: notebook
  arguments:
    - name: processed_file
      value: i15-1-81948-pe2AD-ae484995-b6fa-440b-8210-e00eb1e1ee06.pe2AD.bragg.nxs
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory

  volumeClaimTemplates:
    - metadata:
        name: tmp
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path

  templates:
  - name: hostpath-mount-example
    container:
      image: docker.io/library/busybox:latest
      command: 
      - tree
      - /dls/session
      volumeMounts:
        - name: session
          mountPath: /dls/session
    volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory

  - name: mount-files
    script:
      image: docker.io/library/python:bookworm
      command: [bash]
      source: |
        echo '{{ .Files.Get "notebooks/summary.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
        echo '{{ .Files.Get "notebooks/requirements.txt" | b64enc }}' | base64 -d > /tmp/requirements.txt
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  - name: convert-notebook
    script:
      image: docker.io/library/python:bookworm
      command: [bash]
      source: |
        python -m venv /tmp/venv
        /tmp/venv/bin/pip install -r /tmp/requirements.txt
        /tmp/venv/bin/python -m ipykernel install --prefix=/tmp/venv --name=venv
        /tmp/venv/bin/python -m papermill /tmp/notebook.ipynb /tmp/notebook-parametrized.ipynb \
          -p inpath 'dls/session/processed/{{`{{workflow.parameters.processed_file}}`}}'
          
        /tmp/venv/bin/python -m jupyter nbconvert --execute --allow-errors --to html --output notebook --output-dir /tmp /tmp/notebook-parametrized.ipynb
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  outputs:
    artifacts:
    - name: diffrac-image
      path: /tmp/result_image.png
      archive:
        none: {}  